# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assetmanagerdialog.ui'
#
# Created: Fri Sep 13 10:46:17 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_asset_manager_ui(object):
    def setupUi(self, asset_manager_ui):
        asset_manager_ui.setObjectName(_fromUtf8("asset_manager_ui"))
        asset_manager_ui.resize(779, 463)
        self.gridLayout_2 = QtGui.QGridLayout(asset_manager_ui)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter = QtGui.QSplitter(asset_manager_ui)
        self.splitter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.splitter.setFrameShadow(QtGui.QFrame.Raised)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ui_le_rootPackagePath = QtGui.QLineEdit(self.tab)
        self.ui_le_rootPackagePath.setObjectName(_fromUtf8("ui_le_rootPackagePath"))
        self.horizontalLayout_2.addWidget(self.ui_le_rootPackagePath)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.ui_cb_packages = QtGui.QComboBox(self.tab)
        self.ui_cb_packages.setObjectName(_fromUtf8("ui_cb_packages"))
        self.gridLayout.addWidget(self.ui_cb_packages, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ui_cb_staticProps = QtGui.QCheckBox(self.tab)
        self.ui_cb_staticProps.setObjectName(_fromUtf8("ui_cb_staticProps"))
        self.horizontalLayout_3.addWidget(self.ui_cb_staticProps)
        self.ui_cb_animatedProps = QtGui.QCheckBox(self.tab)
        self.ui_cb_animatedProps.setObjectName(_fromUtf8("ui_cb_animatedProps"))
        self.horizontalLayout_3.addWidget(self.ui_cb_animatedProps)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ui_cb_interactiveProps = QtGui.QCheckBox(self.tab)
        self.ui_cb_interactiveProps.setObjectName(_fromUtf8("ui_cb_interactiveProps"))
        self.horizontalLayout_4.addWidget(self.ui_cb_interactiveProps)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.ui_tbl_PropNodes = QtGui.QTableView(self.tab)
        self.ui_tbl_PropNodes.setAlternatingRowColors(True)
        self.ui_tbl_PropNodes.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.ui_tbl_PropNodes.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.ui_tbl_PropNodes.setShowGrid(False)
        self.ui_tbl_PropNodes.setObjectName(_fromUtf8("ui_tbl_PropNodes"))
        self.ui_tbl_PropNodes.horizontalHeader().setStretchLastSection(True)
        self.ui_tbl_PropNodes.verticalHeader().setVisible(False)
        self.ui_tbl_PropNodes.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout.addWidget(self.ui_tbl_PropNodes, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(92, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 367, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.hlayout_opengl = QtGui.QVBoxLayout(self.widget)
        self.hlayout_opengl.setMargin(0)
        self.hlayout_opengl.setObjectName(_fromUtf8("hlayout_opengl"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(308, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.ui_btn_toggleGrid = QtGui.QPushButton(self.widget)
        self.ui_btn_toggleGrid.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ui_btn_toggleGrid.setObjectName(_fromUtf8("ui_btn_toggleGrid"))
        self.horizontalLayout.addWidget(self.ui_btn_toggleGrid)
        self.ui_btn_toggleAxis = QtGui.QPushButton(self.widget)
        self.ui_btn_toggleAxis.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ui_btn_toggleAxis.setObjectName(_fromUtf8("ui_btn_toggleAxis"))
        self.horizontalLayout.addWidget(self.ui_btn_toggleAxis)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.hlayout_opengl.addLayout(self.horizontalLayout)
        self.ui_oglCanvas = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_oglCanvas.sizePolicy().hasHeightForWidth())
        self.ui_oglCanvas.setSizePolicy(sizePolicy)
        self.ui_oglCanvas.setStyleSheet(_fromUtf8("background-color:rgb(44, 44, 44)"))
        self.ui_oglCanvas.setObjectName(_fromUtf8("ui_oglCanvas"))
        self.hlayout_opengl.addWidget(self.ui_oglCanvas)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(asset_manager_ui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(asset_manager_ui)

    def retranslateUi(self, asset_manager_ui):
        asset_manager_ui.setWindowTitle(QtGui.QApplication.translate("asset_manager_ui", "ATemp", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_le_rootPackagePath.setText(QtGui.QApplication.translate("asset_manager_ui", "D:\\Projects\\DH5\\DH5\\data_workspace\\packages\\", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("asset_manager_ui", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_cb_staticProps.setText(QtGui.QApplication.translate("asset_manager_ui", "Static", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_cb_animatedProps.setText(QtGui.QApplication.translate("asset_manager_ui", "Animated", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_cb_interactiveProps.setText(QtGui.QApplication.translate("asset_manager_ui", "Interactive", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("asset_manager_ui", "Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("asset_manager_ui", "Make Lib Item", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("asset_manager_ui", "Lib Master", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_toggleGrid.setText(QtGui.QApplication.translate("asset_manager_ui", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_toggleAxis.setText(QtGui.QApplication.translate("asset_manager_ui", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("asset_manager_ui", "Human", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    asset_manager_ui = QtGui.QDialog()
    ui = Ui_asset_manager_ui()
    ui.setupUi(asset_manager_ui)
    asset_manager_ui.show()
    sys.exit(app.exec_())

