# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Maya_Tools\Pipeline\UI\..\media\main_UI.ui'
#
# Created: Wed May 06 22:23:26 2015
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 462)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.type_selecter = QtGui.QTabWidget(self.centralwidget)
        self.type_selecter.setObjectName("type_selecter")
        self.NewArt = QtGui.QWidget()
        self.NewArt.setObjectName("NewArt")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.NewArt)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_5 = QtGui.QLabel(self.NewArt)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_28.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.game_dropdown = QtGui.QComboBox(self.NewArt)
        self.game_dropdown.setObjectName("game_dropdown")
        self.game_dropdown.addItem("")
        self.verticalLayout_5.addWidget(self.game_dropdown)
        self.type_dropdown = QtGui.QComboBox(self.NewArt)
        self.type_dropdown.setObjectName("type_dropdown")
        self.type_dropdown.addItem("")
        self.verticalLayout_5.addWidget(self.type_dropdown)
        self.idenifier_dropdown = QtGui.QLineEdit(self.NewArt)
        self.idenifier_dropdown.setObjectName("idenifier_dropdown")
        self.verticalLayout_5.addWidget(self.idenifier_dropdown)
        self.side_dropdown = QtGui.QComboBox(self.NewArt)
        self.side_dropdown.setObjectName("side_dropdown")
        self.side_dropdown.addItem("")
        self.verticalLayout_5.addWidget(self.side_dropdown)
        self.name_box = QtGui.QLineEdit(self.NewArt)
        self.name_box.setObjectName("name_box")
        self.verticalLayout_5.addWidget(self.name_box)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.NewArt)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem2)
        self.setup_new_file = QtGui.QPushButton(self.NewArt)
        self.setup_new_file.setObjectName("setup_new_file")
        self.horizontalLayout_30.addWidget(self.setup_new_file)
        self.cancel_new_art = QtGui.QPushButton(self.NewArt)
        self.cancel_new_art.setObjectName("cancel_new_art")
        self.horizontalLayout_30.addWidget(self.cancel_new_art)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.type_selecter.addTab(self.NewArt, "")
        self.game2d = QtGui.QWidget()
        self.game2d.setObjectName("game2d")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.game2d)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Pipeline2d = QtGui.QLabel(self.game2d)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Pipeline2d.setFont(font)
        self.Pipeline2d.setObjectName("Pipeline2d")
        self.verticalLayout.addWidget(self.Pipeline2d)
        self.tool_selecter = QtGui.QToolBox(self.game2d)
        self.tool_selecter.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_selecter.sizePolicy().hasHeightForWidth())
        self.tool_selecter.setSizePolicy(sizePolicy)
        self.tool_selecter.setMinimumSize(QtCore.QSize(440, 327))
        self.tool_selecter.setObjectName("tool_selecter")
        self.page = QtGui.QWidget()
        self.page.setEnabled(True)
        self.page.setGeometry(QtCore.QRect(0, 0, 892, 274))
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.select_files_hbox = QtGui.QHBoxLayout()
        self.select_files_hbox.setObjectName("select_files_hbox")
        self.select_files_button_2d = QtGui.QPushButton(self.page)
        self.select_files_button_2d.setObjectName("select_files_button_2d")
        self.select_files_hbox.addWidget(self.select_files_button_2d)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.select_files_hbox.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.select_files_hbox)
        self.file_to_import_hbox = QtGui.QHBoxLayout()
        self.file_to_import_hbox.setObjectName("file_to_import_hbox")
        self.files_to_import = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.files_to_import.setFont(font)
        self.files_to_import.setObjectName("files_to_import")
        self.file_to_import_hbox.addWidget(self.files_to_import)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.file_to_import_hbox.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.file_to_import_hbox)
        self.file_name_box_hbox = QtGui.QHBoxLayout()
        self.file_name_box_hbox.setObjectName("file_name_box_hbox")
        self.files_to_import_2d = QtGui.QScrollArea(self.page)
        self.files_to_import_2d.setWidgetResizable(True)
        self.files_to_import_2d.setObjectName("files_to_import_2d")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 870, 113))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.delete_me_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.delete_me_2.setObjectName("delete_me_2")
        self.horizontalLayout_3.addWidget(self.delete_me_2)
        self.files_to_import_2d.setWidget(self.scrollAreaWidgetContents)
        self.file_name_box_hbox.addWidget(self.files_to_import_2d)
        self.verticalLayout_2.addLayout(self.file_name_box_hbox)
        self.render_passes_callout_hbox = QtGui.QHBoxLayout()
        self.render_passes_callout_hbox.setObjectName("render_passes_callout_hbox")
        self.render_passes_callout = QtGui.QLabel(self.page)
        self.render_passes_callout.setObjectName("render_passes_callout")
        self.render_passes_callout_hbox.addWidget(self.render_passes_callout)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.render_passes_callout_hbox.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.render_passes_callout_hbox)
        self.render_pass_grid = QtGui.QGridLayout()
        self.render_pass_grid.setObjectName("render_pass_grid")
        self.diff_nos = QtGui.QCheckBox(self.page)
        self.diff_nos.setChecked(True)
        self.diff_nos.setObjectName("diff_nos")
        self.render_pass_grid.addWidget(self.diff_nos, 0, 0, 1, 1)
        self.beauty = QtGui.QCheckBox(self.page)
        self.beauty.setObjectName("beauty")
        self.render_pass_grid.addWidget(self.beauty, 0, 2, 1, 1)
        self.diffuse = QtGui.QCheckBox(self.page)
        self.diffuse.setObjectName("diffuse")
        self.render_pass_grid.addWidget(self.diffuse, 1, 2, 1, 1)
        self.shadow = QtGui.QCheckBox(self.page)
        self.shadow.setChecked(True)
        self.shadow.setObjectName("shadow")
        self.render_pass_grid.addWidget(self.shadow, 1, 0, 1, 1)
        self.specularity = QtGui.QCheckBox(self.page)
        self.specularity.setChecked(True)
        self.specularity.setObjectName("specularity")
        self.render_pass_grid.addWidget(self.specularity, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.render_pass_grid)
        self.tool_selecter.addItem(self.page, "")
        self.city_builder = QtGui.QWidget()
        self.city_builder.setGeometry(QtCore.QRect(0, 0, 892, 274))
        self.city_builder.setObjectName("city_builder")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.city_builder)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.city_builder_hbox = QtGui.QHBoxLayout()
        self.city_builder_hbox.setObjectName("city_builder_hbox")
        self.city_builder_cbox = QtGui.QCheckBox(self.city_builder)
        self.city_builder_cbox.setObjectName("city_builder_cbox")
        self.city_builder_hbox.addWidget(self.city_builder_cbox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.city_builder_hbox.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.city_builder_hbox)
        self.fit_view_distance_hbox = QtGui.QHBoxLayout()
        self.fit_view_distance_hbox.setObjectName("fit_view_distance_hbox")
        self.fit_view_distance_label = QtGui.QLabel(self.city_builder)
        self.fit_view_distance_label.setEnabled(True)
        self.fit_view_distance_label.setObjectName("fit_view_distance_label")
        self.fit_view_distance_hbox.addWidget(self.fit_view_distance_label)
        self.view_fit_distance_sb = QtGui.QDoubleSpinBox(self.city_builder)
        self.view_fit_distance_sb.setEnabled(False)
        self.view_fit_distance_sb.setMaximum(1.0)
        self.view_fit_distance_sb.setProperty("value", 0.5)
        self.view_fit_distance_sb.setObjectName("view_fit_distance_sb")
        self.fit_view_distance_hbox.addWidget(self.view_fit_distance_sb)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.fit_view_distance_hbox.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.fit_view_distance_hbox)
        self.number_of_angles_hbox = QtGui.QHBoxLayout()
        self.number_of_angles_hbox.setObjectName("number_of_angles_hbox")
        self.number_of_angles_lable = QtGui.QLabel(self.city_builder)
        self.number_of_angles_lable.setEnabled(True)
        self.number_of_angles_lable.setObjectName("number_of_angles_lable")
        self.number_of_angles_hbox.addWidget(self.number_of_angles_lable)
        self.number_of_angles_sbox = QtGui.QSpinBox(self.city_builder)
        self.number_of_angles_sbox.setEnabled(False)
        self.number_of_angles_sbox.setMinimum(1)
        self.number_of_angles_sbox.setProperty("value", 8)
        self.number_of_angles_sbox.setObjectName("number_of_angles_sbox")
        self.number_of_angles_hbox.addWidget(self.number_of_angles_sbox)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.number_of_angles_hbox.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.number_of_angles_hbox)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.tool_selecter.addItem(self.city_builder, "")
        self.verticalLayout.addWidget(self.tool_selecter)
        self.bottom_hbox = QtGui.QHBoxLayout()
        self.bottom_hbox.setObjectName("bottom_hbox")
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottom_hbox.addItem(spacerItem10)
        self.import_button_2d = QtGui.QPushButton(self.game2d)
        self.import_button_2d.setObjectName("import_button_2d")
        self.bottom_hbox.addWidget(self.import_button_2d)
        self.cancel_button_2d = QtGui.QPushButton(self.game2d)
        self.cancel_button_2d.setObjectName("cancel_button_2d")
        self.bottom_hbox.addWidget(self.cancel_button_2d)
        self.verticalLayout.addLayout(self.bottom_hbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.type_selecter.addTab(self.game2d, "")
        self.game3d = QtGui.QWidget()
        self.game3d.setObjectName("game3d")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.game3d)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.Pipeline3d_3 = QtGui.QLabel(self.game3d)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Pipeline3d_3.setFont(font)
        self.Pipeline3d_3.setObjectName("Pipeline3d_3")
        self.horizontalLayout_23.addWidget(self.Pipeline3d_3)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.select_files_hbox_4 = QtGui.QHBoxLayout()
        self.select_files_hbox_4.setObjectName("select_files_hbox_4")
        self.select_files_button_3d = QtGui.QPushButton(self.game3d)
        self.select_files_button_3d.setObjectName("select_files_button_3d")
        self.select_files_hbox_4.addWidget(self.select_files_button_3d)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.select_files_hbox_4.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.select_files_hbox_4)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.files_to_import_4 = QtGui.QLabel(self.game3d)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.files_to_import_4.setFont(font)
        self.files_to_import_4.setObjectName("files_to_import_4")
        self.horizontalLayout_25.addWidget(self.files_to_import_4)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.files_to_import_3d = QtGui.QScrollArea(self.game3d)
        self.files_to_import_3d.setWidgetResizable(True)
        self.files_to_import_3d.setObjectName("files_to_import_3d")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 890, 221))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.delete_me = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.delete_me.setObjectName("delete_me")
        self.horizontalLayout_21.addWidget(self.delete_me)
        self.files_to_import_3d.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_20.addWidget(self.files_to_import_3d)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem14)
        self.export_animation = QtGui.QPushButton(self.game3d)
        self.export_animation.setObjectName("export_animation")
        self.horizontalLayout_24.addWidget(self.export_animation)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.line_2 = QtGui.QFrame(self.game3d)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem15)
        self.import_button_3d = QtGui.QPushButton(self.game3d)
        self.import_button_3d.setObjectName("import_button_3d")
        self.horizontalLayout_26.addWidget(self.import_button_3d)
        self.cancel_button_3d = QtGui.QPushButton(self.game3d)
        self.cancel_button_3d.setObjectName("cancel_button_3d")
        self.horizontalLayout_26.addWidget(self.cancel_button_3d)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.type_selecter.addTab(self.game3d, "")
        self.horizontalLayout.addWidget(self.type_selecter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action3d_Game = QtGui.QAction(MainWindow)
        self.action3d_Game.setCheckable(True)
        self.action3d_Game.setObjectName("action3d_Game")
        self.actionCity_Builder = QtGui.QAction(MainWindow)
        self.actionCity_Builder.setObjectName("actionCity_Builder")
        self.actionPre_Rendered = QtGui.QAction(MainWindow)
        self.actionPre_Rendered.setObjectName("actionPre_Rendered")
        self.action2d_Game = QtGui.QAction(MainWindow)
        self.action2d_Game.setObjectName("action2d_Game")

        self.retranslateUi(MainWindow)
        self.type_selecter.setCurrentIndex(0)
        self.tool_selecter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "File Namer", None, QtGui.QApplication.UnicodeUTF8))
        self.game_dropdown.setItemText(0, QtGui.QApplication.translate("MainWindow", "Game", None, QtGui.QApplication.UnicodeUTF8))
        self.type_dropdown.setItemText(0, QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.idenifier_dropdown.setText(QtGui.QApplication.translate("MainWindow", "What is it? (always lower cased)", None, QtGui.QApplication.UnicodeUTF8))
        self.side_dropdown.setItemText(0, QtGui.QApplication.translate("MainWindow", "side", None, QtGui.QApplication.UnicodeUTF8))
        self.name_box.setText(QtGui.QApplication.translate("MainWindow", "Name (always lower cased)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Final Name will be", None, QtGui.QApplication.UnicodeUTF8))
        self.setup_new_file.setText(QtGui.QApplication.translate("MainWindow", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_new_art.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.type_selecter.setTabText(self.type_selecter.indexOf(self.NewArt), QtGui.QApplication.translate("MainWindow", "New Art", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipeline2d.setText(QtGui.QApplication.translate("MainWindow", "2d Pipeline", None, QtGui.QApplication.UnicodeUTF8))
        self.select_files_button_2d.setText(QtGui.QApplication.translate("MainWindow", "Select Files to import", None, QtGui.QApplication.UnicodeUTF8))
        self.files_to_import.setText(QtGui.QApplication.translate("MainWindow", "Files To Import", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_me_2.setText(QtGui.QApplication.translate("MainWindow", "delete_me", None, QtGui.QApplication.UnicodeUTF8))
        self.render_passes_callout.setText(QtGui.QApplication.translate("MainWindow", "Render Passes (recommended are checked)", None, QtGui.QApplication.UnicodeUTF8))
        self.diff_nos.setText(QtGui.QApplication.translate("MainWindow", "Diffuse without Shadow", None, QtGui.QApplication.UnicodeUTF8))
        self.beauty.setText(QtGui.QApplication.translate("MainWindow", "Beauty", None, QtGui.QApplication.UnicodeUTF8))
        self.diffuse.setText(QtGui.QApplication.translate("MainWindow", "Diffuse With Shadow", None, QtGui.QApplication.UnicodeUTF8))
        self.shadow.setText(QtGui.QApplication.translate("MainWindow", "Shadow", None, QtGui.QApplication.UnicodeUTF8))
        self.specularity.setText(QtGui.QApplication.translate("MainWindow", "Specularity", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_selecter.setItemText(self.tool_selecter.indexOf(self.page), QtGui.QApplication.translate("MainWindow", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.city_builder_cbox.setText(QtGui.QApplication.translate("MainWindow", "City Builder?", None, QtGui.QApplication.UnicodeUTF8))
        self.fit_view_distance_label.setText(QtGui.QApplication.translate("MainWindow", "Fit View Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.number_of_angles_lable.setText(QtGui.QApplication.translate("MainWindow", "Number of Angles", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_selecter.setItemText(self.tool_selecter.indexOf(self.city_builder), QtGui.QApplication.translate("MainWindow", "City Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button_2d.setText(QtGui.QApplication.translate("MainWindow", "Import Files", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button_2d.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.type_selecter.setTabText(self.type_selecter.indexOf(self.game2d), QtGui.QApplication.translate("MainWindow", "2d Game", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipeline3d_3.setText(QtGui.QApplication.translate("MainWindow", "3d Pipeline", None, QtGui.QApplication.UnicodeUTF8))
        self.select_files_button_3d.setText(QtGui.QApplication.translate("MainWindow", "Select Files to import", None, QtGui.QApplication.UnicodeUTF8))
        self.files_to_import_4.setText(QtGui.QApplication.translate("MainWindow", "Files To Import", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_me.setText(QtGui.QApplication.translate("MainWindow", "delete_me", None, QtGui.QApplication.UnicodeUTF8))
        self.export_animation.setText(QtGui.QApplication.translate("MainWindow", "export animation on current file to game", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button_3d.setText(QtGui.QApplication.translate("MainWindow", "Import Files", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button_3d.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.type_selecter.setTabText(self.type_selecter.indexOf(self.game3d), QtGui.QApplication.translate("MainWindow", "3d Game", None, QtGui.QApplication.UnicodeUTF8))
        self.action3d_Game.setText(QtGui.QApplication.translate("MainWindow", "3d Game", None, QtGui.QApplication.UnicodeUTF8))
        self.action3d_Game.setStatusTip(QtGui.QApplication.translate("MainWindow", "To produce art for a 3d game select here", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCity_Builder.setText(QtGui.QApplication.translate("MainWindow", "City Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPre_Rendered.setText(QtGui.QApplication.translate("MainWindow", "Pre Rendered", None, QtGui.QApplication.UnicodeUTF8))
        self.action2d_Game.setText(QtGui.QApplication.translate("MainWindow", "2d Game", None, QtGui.QApplication.UnicodeUTF8))

