# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lightmapbakerdialog.ui'
#
# Created: Tue Jun 18 14:18:43 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName(_fromUtf8("dialog"))
        dialog.resize(247, 431)
        dialog.setStyleSheet(_fromUtf8(""))
        self.gridLayout_3 = QtGui.QGridLayout(dialog)
        self.gridLayout_3.setMargin(5)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.ui_groupBakeMaps = QtGui.QGroupBox(dialog)
        self.ui_groupBakeMaps.setObjectName(_fromUtf8("ui_groupBakeMaps"))
        self.gridLayout = QtGui.QGridLayout(self.ui_groupBakeMaps)
        self.gridLayout.setMargin(5)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ui_chb_bakeLightMap = QtGui.QCheckBox(self.ui_groupBakeMaps)
        self.ui_chb_bakeLightMap.setChecked(True)
        self.ui_chb_bakeLightMap.setObjectName(_fromUtf8("ui_chb_bakeLightMap"))
        self.horizontalLayout_2.addWidget(self.ui_chb_bakeLightMap)
        self.ui_chb_bakeAO = QtGui.QCheckBox(self.ui_groupBakeMaps)
        self.ui_chb_bakeAO.setObjectName(_fromUtf8("ui_chb_bakeAO"))
        self.horizontalLayout_2.addWidget(self.ui_chb_bakeAO)
        self.ui_chb_bakeDirectionalLM = QtGui.QCheckBox(self.ui_groupBakeMaps)
        self.ui_chb_bakeDirectionalLM.setObjectName(_fromUtf8("ui_chb_bakeDirectionalLM"))
        self.horizontalLayout_2.addWidget(self.ui_chb_bakeDirectionalLM)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.ui_lst_lmLayers = QtGui.QListWidget(self.ui_groupBakeMaps)
        self.ui_lst_lmLayers.setMaximumSize(QtCore.QSize(16777215, 60))
        self.ui_lst_lmLayers.setObjectName(_fromUtf8("ui_lst_lmLayers"))
        self.verticalLayout.addWidget(self.ui_lst_lmLayers)
        self.ui_btn_BakeLightmap = QtGui.QPushButton(self.ui_groupBakeMaps)
        self.ui_btn_BakeLightmap.setMinimumSize(QtCore.QSize(0, 40))
        self.ui_btn_BakeLightmap.setObjectName(_fromUtf8("ui_btn_BakeLightmap"))
        self.verticalLayout.addWidget(self.ui_btn_BakeLightmap)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ui_btn_openBakedImages = QtGui.QPushButton(self.ui_groupBakeMaps)
        self.ui_btn_openBakedImages.setMinimumSize(QtCore.QSize(120, 0))
        self.ui_btn_openBakedImages.setObjectName(_fromUtf8("ui_btn_openBakedImages"))
        self.horizontalLayout_3.addWidget(self.ui_btn_openBakedImages)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.ui_btn_openBakeDirectory = QtGui.QPushButton(self.ui_groupBakeMaps)
        self.ui_btn_openBakeDirectory.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../img/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_btn_openBakeDirectory.setIcon(icon)
        self.ui_btn_openBakeDirectory.setObjectName(_fromUtf8("ui_btn_openBakeDirectory"))
        self.horizontalLayout_3.addWidget(self.ui_btn_openBakeDirectory)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.ui_groupBakeMaps, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btn_settings = QtGui.QPushButton(dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy)
        self.btn_settings.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_settings.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../img/cog.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon1)
        self.btn_settings.setIconSize(QtCore.QSize(20, 20))
        self.btn_settings.setObjectName(_fromUtf8("btn_settings"))
        self.gridLayout_2.addWidget(self.btn_settings, 0, 0, 1, 1)
        self.ui_btn_bakeMode = QtGui.QPushButton(dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_btn_bakeMode.sizePolicy().hasHeightForWidth())
        self.ui_btn_bakeMode.setSizePolicy(sizePolicy)
        self.ui_btn_bakeMode.setMinimumSize(QtCore.QSize(0, 22))
        self.ui_btn_bakeMode.setMaximumSize(QtCore.QSize(16777215, 24))
        self.ui_btn_bakeMode.setCheckable(True)
        self.ui_btn_bakeMode.setObjectName(_fromUtf8("ui_btn_bakeMode"))
        self.gridLayout_2.addWidget(self.ui_btn_bakeMode, 0, 1, 1, 1)
        self.ui_btn_RenderPreview = QtGui.QPushButton(dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_btn_RenderPreview.sizePolicy().hasHeightForWidth())
        self.ui_btn_RenderPreview.setSizePolicy(sizePolicy)
        self.ui_btn_RenderPreview.setMinimumSize(QtCore.QSize(231, 191))
        self.ui_btn_RenderPreview.setObjectName(_fromUtf8("ui_btn_RenderPreview"))
        self.gridLayout_2.addWidget(self.ui_btn_RenderPreview, 1, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QtGui.QApplication.translate("dialog", "LightmapBaker", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_groupBakeMaps.setTitle(QtGui.QApplication.translate("dialog", "Bake Maps", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_chb_bakeLightMap.setText(QtGui.QApplication.translate("dialog", "Lightmap", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_chb_bakeAO.setText(QtGui.QApplication.translate("dialog", "AO", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_chb_bakeDirectionalLM.setText(QtGui.QApplication.translate("dialog", "Directional LM", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_BakeLightmap.setToolTip(QtGui.QApplication.translate("dialog", "<html><head/><body><p>Bakes the currently selected lightmap types</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_BakeLightmap.setText(QtGui.QApplication.translate("dialog", "Bake", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_openBakedImages.setText(QtGui.QApplication.translate("dialog", "Open Baked Images", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_settings.setToolTip(QtGui.QApplication.translate("dialog", "<html><head/><body><p>Setting for the the tool</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_bakeMode.setToolTip(QtGui.QApplication.translate("dialog", "<html><head/><body><p>Prepares the scene for baking.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_bakeMode.setText(QtGui.QApplication.translate("dialog", "Enter Baking Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_RenderPreview.setToolTip(QtGui.QApplication.translate("dialog", "<html><head/><body><p>Render a preview of the current scene. Press ESC key to stop the render.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_btn_RenderPreview.setText(QtGui.QApplication.translate("dialog", "Click to Preview", None, QtGui.QApplication.UnicodeUTF8))

