# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Art_Tools\workspace\art_pipeline\UI\Raw\Artist_UI.ui'
#
# Created: Tue Dec 01 10:24:35 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ArtTools(object):
    def setupUi(self, ArtTools):
        ArtTools.setObjectName("ArtTools")
        ArtTools.resize(500, 300)
        ArtTools.setMinimumSize(QtCore.QSize(500, 300))
        ArtTools.setMaximumSize(QtCore.QSize(500, 300))
        self.verticalLayout = QtGui.QVBoxLayout(ArtTools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopTab = QtGui.QTabWidget(ArtTools)
        self.TopTab.setStyleSheet("")
        self.TopTab.setObjectName("TopTab")
        self.FolderSetup = QtGui.QWidget()
        self.FolderSetup.setObjectName("FolderSetup")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.FolderSetup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(self.FolderSetup)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SlotsGameName = QtGui.QLabel(self.FolderSetup)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SlotsGameName.setFont(font)
        self.SlotsGameName.setObjectName("SlotsGameName")
        self.horizontalLayout_3.addWidget(self.SlotsGameName)
        self.SlotsGameNameInput = QtGui.QLineEdit(self.FolderSetup)
        self.SlotsGameNameInput.setObjectName("SlotsGameNameInput")
        self.horizontalLayout_3.addWidget(self.SlotsGameNameInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GameType = QtGui.QLabel(self.FolderSetup)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.GameType.setFont(font)
        self.GameType.setObjectName("GameType")
        self.horizontalLayout_2.addWidget(self.GameType)
        self.GameTypeComboBox = QtGui.QComboBox(self.FolderSetup)
        self.GameTypeComboBox.setObjectName("GameTypeComboBox")
        self.GameTypeComboBox.addItem("")
        self.GameTypeComboBox.addItem("")
        self.GameTypeComboBox.addItem("")
        self.GameTypeComboBox.addItem("")
        self.GameTypeComboBox.addItem("")
        self.GameTypeComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.GameTypeComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.NumberOfPicks = QtGui.QLabel(self.FolderSetup)
        self.NumberOfPicks.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NumberOfPicks.setFont(font)
        self.NumberOfPicks.setObjectName("NumberOfPicks")
        self.horizontalLayout_5.addWidget(self.NumberOfPicks)
        self.NumberOfPicksInput = QtGui.QLineEdit(self.FolderSetup)
        self.NumberOfPicksInput.setEnabled(True)
        self.NumberOfPicksInput.setObjectName("NumberOfPicksInput")
        self.horizontalLayout_5.addWidget(self.NumberOfPicksInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.RotelleCheckBox = QtGui.QCheckBox(self.FolderSetup)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.RotelleCheckBox.setFont(font)
        self.RotelleCheckBox.setObjectName("RotelleCheckBox")
        self.horizontalLayout_10.addWidget(self.RotelleCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.TopTab.addTab(self.FolderSetup, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.BingoLabel = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.BingoLabel.setFont(font)
        self.BingoLabel.setObjectName("BingoLabel")
        self.horizontalLayout_7.addWidget(self.BingoLabel)
        self.BingoGameInput = QtGui.QLineEdit(self.tab)
        self.BingoGameInput.setObjectName("BingoGameInput")
        self.horizontalLayout_7.addWidget(self.BingoGameInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtGui.QSpacerItem(20, 147, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.TopTab.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SlotsFolderLabelCheck = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SlotsFolderLabelCheck.setFont(font)
        self.SlotsFolderLabelCheck.setObjectName("SlotsFolderLabelCheck")
        self.horizontalLayout.addWidget(self.SlotsFolderLabelCheck)
        self.SlotsFolderLocationCheck = QtGui.QLineEdit(self.tab_2)
        self.SlotsFolderLocationCheck.setObjectName("SlotsFolderLocationCheck")
        self.horizontalLayout.addWidget(self.SlotsFolderLocationCheck)
        self.SlotsFolderCheck = QtGui.QToolButton(self.tab_2)
        self.SlotsFolderCheck.setObjectName("SlotsFolderCheck")
        self.horizontalLayout.addWidget(self.SlotsFolderCheck)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.BingoFolderLabeCheck = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.BingoFolderLabeCheck.setFont(font)
        self.BingoFolderLabeCheck.setObjectName("BingoFolderLabeCheck")
        self.horizontalLayout_11.addWidget(self.BingoFolderLabeCheck)
        self.BingoFolderLocationCheck = QtGui.QLineEdit(self.tab_2)
        self.BingoFolderLocationCheck.setObjectName("BingoFolderLocationCheck")
        self.horizontalLayout_11.addWidget(self.BingoFolderLocationCheck)
        self.BingoFolderCheck = QtGui.QToolButton(self.tab_2)
        self.BingoFolderCheck.setObjectName("BingoFolderCheck")
        self.horizontalLayout_11.addWidget(self.BingoFolderCheck)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtGui.QSpacerItem(20, 106, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.TopTab.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.OpenTiramisu = QtGui.QPushButton(self.tab_3)
        self.OpenTiramisu.setObjectName("OpenTiramisu")
        self.horizontalLayout_4.addWidget(self.OpenTiramisu)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(20, 174, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.TopTab.addTab(self.tab_3, "")
        self.Setup = QtGui.QWidget()
        self.Setup.setObjectName("Setup")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Setup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtGui.QLabel(self.Setup)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.SlotsFolderLabel = QtGui.QLabel(self.Setup)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SlotsFolderLabel.setFont(font)
        self.SlotsFolderLabel.setObjectName("SlotsFolderLabel")
        self.horizontalLayout_6.addWidget(self.SlotsFolderLabel)
        self.SlotsFolderLocation = QtGui.QLineEdit(self.Setup)
        self.SlotsFolderLocation.setObjectName("SlotsFolderLocation")
        self.horizontalLayout_6.addWidget(self.SlotsFolderLocation)
        self.SlotsFolder = QtGui.QToolButton(self.Setup)
        self.SlotsFolder.setObjectName("SlotsFolder")
        self.horizontalLayout_6.addWidget(self.SlotsFolder)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.BingoFolderLabel = QtGui.QLabel(self.Setup)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.BingoFolderLabel.setFont(font)
        self.BingoFolderLabel.setObjectName("BingoFolderLabel")
        self.horizontalLayout_8.addWidget(self.BingoFolderLabel)
        self.BingoFolderLocation = QtGui.QLineEdit(self.Setup)
        self.BingoFolderLocation.setObjectName("BingoFolderLocation")
        self.horizontalLayout_8.addWidget(self.BingoFolderLocation)
        self.BingoFolder = QtGui.QToolButton(self.Setup)
        self.BingoFolder.setObjectName("BingoFolder")
        self.horizontalLayout_8.addWidget(self.BingoFolder)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem6 = QtGui.QSpacerItem(20, 166, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.TopTab.addTab(self.Setup, "")
        self.verticalLayout.addWidget(self.TopTab)
        self.buttonBox = QtGui.QDialogButtonBox(ArtTools)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ArtTools)
        self.TopTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ArtTools)

    def retranslateUi(self, ArtTools):
        ArtTools.setWindowTitle(QtGui.QApplication.translate("ArtTools", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setToolTip(QtGui.QApplication.translate("ArtTools", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setWhatsThis(QtGui.QApplication.translate("ArtTools", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ArtTools", "Make a new slots room", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsGameName.setText(QtGui.QApplication.translate("ArtTools", "Game Name", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsGameNameInput.setText(QtGui.QApplication.translate("ArtTools", "Example: LuckyLotus", None, QtGui.QApplication.UnicodeUTF8))
        self.GameType.setText(QtGui.QApplication.translate("ArtTools", "Game Type", None, QtGui.QApplication.UnicodeUTF8))
        self.GameTypeComboBox.setItemText(0, QtGui.QApplication.translate("ArtTools", "Type?", None, QtGui.QApplication.UnicodeUTF8))
        self.GameTypeComboBox.setItemText(1, QtGui.QApplication.translate("ArtTools", "Theamed", None, QtGui.QApplication.UnicodeUTF8))
        self.GameTypeComboBox.setItemText(2, QtGui.QApplication.translate("ArtTools", "Pick till you poop", None, QtGui.QApplication.UnicodeUTF8))
        self.GameTypeComboBox.setItemText(3, QtGui.QApplication.translate("ArtTools", "Fixed Pick", None, QtGui.QApplication.UnicodeUTF8))
        self.GameTypeComboBox.setItemText(4, QtGui.QApplication.translate("ArtTools", "Free Spin", None, QtGui.QApplication.UnicodeUTF8))
        self.GameTypeComboBox.setItemText(5, QtGui.QApplication.translate("ArtTools", "Modified", None, QtGui.QApplication.UnicodeUTF8))
        self.NumberOfPicks.setText(QtGui.QApplication.translate("ArtTools", "Number of Picks", None, QtGui.QApplication.UnicodeUTF8))
        self.NumberOfPicksInput.setText(QtGui.QApplication.translate("ArtTools", "Leave Alone if not needed.", None, QtGui.QApplication.UnicodeUTF8))
        self.RotelleCheckBox.setText(QtGui.QApplication.translate("ArtTools", "Rotelle", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setTabText(self.TopTab.indexOf(self.FolderSetup), QtGui.QApplication.translate("ArtTools", "Slots", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ArtTools", "Make a new bingo room", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoLabel.setText(QtGui.QApplication.translate("ArtTools", "Game Name", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoGameInput.setText(QtGui.QApplication.translate("ArtTools", "Example: TheDrumStickRedemption", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setTabText(self.TopTab.indexOf(self.tab), QtGui.QApplication.translate("ArtTools", "Bingo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ArtTools", "Select a folder below and hit ok and it will check your art.", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsFolderLabelCheck.setText(QtGui.QApplication.translate("ArtTools", "Slots Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsFolderCheck.setText(QtGui.QApplication.translate("ArtTools", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoFolderLabeCheck.setText(QtGui.QApplication.translate("ArtTools", "Bingo Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoFolderCheck.setText(QtGui.QApplication.translate("ArtTools", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setTabText(self.TopTab.indexOf(self.tab_2), QtGui.QApplication.translate("ArtTools", "Art Check", None, QtGui.QApplication.UnicodeUTF8))
        self.OpenTiramisu.setText(QtGui.QApplication.translate("ArtTools", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setTabText(self.TopTab.indexOf(self.tab_3), QtGui.QApplication.translate("ArtTools", "Run Tiramisu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ArtTools", "Tell us where your stuff lives!", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsFolderLabel.setText(QtGui.QApplication.translate("ArtTools", "Slots Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsFolder.setText(QtGui.QApplication.translate("ArtTools", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoFolderLabel.setText(QtGui.QApplication.translate("ArtTools", "Bingo Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoFolder.setText(QtGui.QApplication.translate("ArtTools", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setTabText(self.TopTab.indexOf(self.Setup), QtGui.QApplication.translate("ArtTools", "Setup", None, QtGui.QApplication.UnicodeUTF8))

