# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Art_Tools\workspace\art_pipeline\UI\Raw\Producer_UI.ui'
#
# Created: Mon Nov 30 13:54:40 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ArtTools(object):
    def setupUi(self, ArtTools):
        ArtTools.setObjectName("ArtTools")
        ArtTools.resize(500, 300)
        ArtTools.setMinimumSize(QtCore.QSize(500, 300))
        ArtTools.setMaximumSize(QtCore.QSize(500, 300))
        self.verticalLayout = QtGui.QVBoxLayout(ArtTools)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopTab = QtGui.QTabWidget(ArtTools)
        self.TopTab.setStyleSheet("")
        self.TopTab.setObjectName("TopTab")
        self.ArtExport = QtGui.QWidget()
        self.ArtExport.setObjectName("ArtExport")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.ArtExport)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(self.ArtExport)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SlotsGameFolder = QtGui.QLabel(self.ArtExport)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SlotsGameFolder.setFont(font)
        self.SlotsGameFolder.setObjectName("SlotsGameFolder")
        self.horizontalLayout.addWidget(self.SlotsGameFolder)
        self.SlotsGameFolderLocation = QtGui.QLineEdit(self.ArtExport)
        self.SlotsGameFolderLocation.setObjectName("SlotsGameFolderLocation")
        self.horizontalLayout.addWidget(self.SlotsGameFolderLocation)
        self.SlotsGameFolderFinder = QtGui.QToolButton(self.ArtExport)
        self.SlotsGameFolderFinder.setObjectName("SlotsGameFolderFinder")
        self.horizontalLayout.addWidget(self.SlotsGameFolderFinder)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.SlotsRoomNumberLabel = QtGui.QLabel(self.ArtExport)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SlotsRoomNumberLabel.setFont(font)
        self.SlotsRoomNumberLabel.setObjectName("SlotsRoomNumberLabel")
        self.horizontalLayout_7.addWidget(self.SlotsRoomNumberLabel)
        self.SlotsRoomNumber = QtGui.QLineEdit(self.ArtExport)
        self.SlotsRoomNumber.setObjectName("SlotsRoomNumber")
        self.horizontalLayout_7.addWidget(self.SlotsRoomNumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.NamingConventnion = QtGui.QComboBox(self.ArtExport)
        self.NamingConventnion.setObjectName("NamingConventnion")
        self.NamingConventnion.addItem("")
        self.NamingConventnion.addItem("")
        self.NamingConventnion.addItem("")
        self.NamingConventnion.addItem("")
        self.NamingConventnion.addItem("")
        self.verticalLayout_3.addWidget(self.NamingConventnion)
        spacerItem = QtGui.QSpacerItem(20, 166, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.TopTab.addTab(self.ArtExport, "")
        self.BingoExport = QtGui.QWidget()
        self.BingoExport.setObjectName("BingoExport")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.BingoExport)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(self.BingoExport)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BingoGameFolderTag = QtGui.QLabel(self.BingoExport)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.BingoGameFolderTag.setFont(font)
        self.BingoGameFolderTag.setObjectName("BingoGameFolderTag")
        self.horizontalLayout_2.addWidget(self.BingoGameFolderTag)
        self.BingoGameFolderLocation = QtGui.QLineEdit(self.BingoExport)
        self.BingoGameFolderLocation.setObjectName("BingoGameFolderLocation")
        self.horizontalLayout_2.addWidget(self.BingoGameFolderLocation)
        self.BingoGameFolderFinder = QtGui.QToolButton(self.BingoExport)
        self.BingoGameFolderFinder.setObjectName("BingoGameFolderFinder")
        self.horizontalLayout_2.addWidget(self.BingoGameFolderFinder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.BingoRoomNumberLabel = QtGui.QLabel(self.BingoExport)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.BingoRoomNumberLabel.setFont(font)
        self.BingoRoomNumberLabel.setObjectName("BingoRoomNumberLabel")
        self.horizontalLayout_8.addWidget(self.BingoRoomNumberLabel)
        self.BingoRoomNumber = QtGui.QLineEdit(self.BingoExport)
        self.BingoRoomNumber.setObjectName("BingoRoomNumber")
        self.horizontalLayout_8.addWidget(self.BingoRoomNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(20, 106, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.TopTab.addTab(self.BingoExport, "")
        self.Setup = QtGui.QWidget()
        self.Setup.setObjectName("Setup")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Setup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtGui.QLabel(self.Setup)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.BingoAssetsFolderLabel = QtGui.QLabel(self.Setup)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.BingoAssetsFolderLabel.setFont(font)
        self.BingoAssetsFolderLabel.setObjectName("BingoAssetsFolderLabel")
        self.horizontalLayout_6.addWidget(self.BingoAssetsFolderLabel)
        self.BingoAssetsFolderLocation = QtGui.QLineEdit(self.Setup)
        self.BingoAssetsFolderLocation.setObjectName("BingoAssetsFolderLocation")
        self.horizontalLayout_6.addWidget(self.BingoAssetsFolderLocation)
        self.BingoAssetsFolder = QtGui.QToolButton(self.Setup)
        self.BingoAssetsFolder.setObjectName("BingoAssetsFolder")
        self.horizontalLayout_6.addWidget(self.BingoAssetsFolder)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtGui.QSpacerItem(20, 166, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.TopTab.addTab(self.Setup, "")
        self.verticalLayout.addWidget(self.TopTab)
        self.buttonBox = QtGui.QDialogButtonBox(ArtTools)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ArtTools)
        self.TopTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ArtTools)

    def retranslateUi(self, ArtTools):
        ArtTools.setWindowTitle(QtGui.QApplication.translate("ArtTools", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setToolTip(QtGui.QApplication.translate("ArtTools", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setWhatsThis(QtGui.QApplication.translate("ArtTools", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ArtTools", "Move art for Slots", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsGameFolder.setText(QtGui.QApplication.translate("ArtTools", "Game Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsGameFolderFinder.setText(QtGui.QApplication.translate("ArtTools", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsRoomNumberLabel.setText(QtGui.QApplication.translate("ArtTools", "Room Number", None, QtGui.QApplication.UnicodeUTF8))
        self.SlotsRoomNumber.setText(QtGui.QApplication.translate("ArtTools", "Room Number", None, QtGui.QApplication.UnicodeUTF8))
        self.NamingConventnion.setItemText(0, QtGui.QApplication.translate("ArtTools", "What Naming Convention?", None, QtGui.QApplication.UnicodeUTF8))
        self.NamingConventnion.setItemText(1, QtGui.QApplication.translate("ArtTools", "Old", None, QtGui.QApplication.UnicodeUTF8))
        self.NamingConventnion.setItemText(2, QtGui.QApplication.translate("ArtTools", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.NamingConventnion.setItemText(3, QtGui.QApplication.translate("ArtTools", "Rotelle", None, QtGui.QApplication.UnicodeUTF8))
        self.NamingConventnion.setItemText(4, QtGui.QApplication.translate("ArtTools", "Rotelle Conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setTabText(self.TopTab.indexOf(self.ArtExport), QtGui.QApplication.translate("ArtTools", "Slots Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ArtTools", "Move art for Bingo", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoGameFolderTag.setText(QtGui.QApplication.translate("ArtTools", "Game Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoGameFolderFinder.setText(QtGui.QApplication.translate("ArtTools", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoRoomNumberLabel.setText(QtGui.QApplication.translate("ArtTools", "Room Number", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoRoomNumber.setText(QtGui.QApplication.translate("ArtTools", "Room Number", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setTabText(self.TopTab.indexOf(self.BingoExport), QtGui.QApplication.translate("ArtTools", "Bingo Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ArtTools", "Tell us where your stuff lives!", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoAssetsFolderLabel.setText(QtGui.QApplication.translate("ArtTools", "BingoAssetsFolder", None, QtGui.QApplication.UnicodeUTF8))
        self.BingoAssetsFolder.setText(QtGui.QApplication.translate("ArtTools", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.TopTab.setTabText(self.TopTab.indexOf(self.Setup), QtGui.QApplication.translate("ArtTools", "Setup", None, QtGui.QApplication.UnicodeUTF8))

